assignment2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 
from django.views.generic.base import TemplateView 
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    url('^', include('friendship.urls'))
]
if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.conf.urls import url
from .import views
from .views import *
# from .views import AuthView, MessengerView, RestAPIView
# from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns=[
    path('',views.indexx,name='indexx'),
    path('pass/<int:uid>',views.password,name='pass'),
    path('login1/',views.user_login,name='login1'),
    # path('signup/', views.SignUp.as_view(), name='signup'),
    path('signup/', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    path('profile/',views.profile,name='profile'),
    path('editprofile/',views.update_profile,name='editprofile'), 
    url(r'^password/$', views.change_password, name='change_password'),

    path('addstudent/',views.addstudent,name='addstudent'),
    path('studentlist/',views.student_list,name='studentlist'),
    path('sendassignment/<int:student_id>/',views.teacher_assignment,name='assignment'),
    path('sendassignments/<int:student_id>/<int:ass_id>/',views.student_assignment,name='s_assignment'),
    path('teacherlist/',views.teacher_list,name='teacherlist'),

    path('trequest/<int:teacher_id>/',views.friendship_add_friend,name='teacher_request'),
    path('request_list/',views.friendship_request_list,name='request_list'),
    path('request_details/<int:friendship_request_id>/',views.friendship_requests_detail,name='requests_detail'),
    path('request_reject/<int:friendship_request_id>/',views.friendship_reject,name='requests_reject'),
    path('request_accept/<int:friendship_request_id>/',views.friendship_accept,name='requests_accept'),
    path('accepted_request/<int:teacher_id>',views.view_friend,name='accepted_request'),
    path('stu_joined/<str:username>',views.view_friends,name='stu_joined'),
    path('accepted_trequest/<int:teacher_id>',views.view_friendss,name='accepted_trequest'),


    path('ass_request/<int:teacher_id>',views.ass_request,name='ass_request'),
    path('studentass_list/',views.studentass_list,name='studentass_list'),
    path('submit_ass/',views.submit_ass,name='submit_ass'),
    path('check_ass/',views.check_ass,name='check_ass'),
    path('remark_ass/<int:student_id>/<int:ass_id>',views.remark_ass,name='remark_ass'),
    path('check_remarks/',views.check_remarks,name='check_remarks'),

    path('messages/<int:teacher_id>',views.messages,name='messages'),
    path('messagess/<int:student_id>',views.messagess,name='messagess'),
    path('messages/',views.check_messages,name='check_messages'),
    path('tmessages/',views.check_tmessages,name='check_tmessages'),
    

]

core/models.py
from django.db import models
from django.contrib.auth.models import UserManager
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.exceptions import ValidationError
from .validators import validate_file_extension,validate_file1_extension
from .signals import *
from datetime import datetime,timedelta
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


def validate_image(image):     
    file_size = image.file.size
    limit_mb = 2
    if file_size >limit_mb * 1024 * 1024:
       raise ValidationError("Max size of file is %s MB" % limit_mb)

ROLE = (
      ('student','student'),
      ('teacher','teacher'),
  )


class User(AbstractUser):
    
    email = models.EmailField(max_length=254)
    username = models.CharField(max_length=254,unique=True)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    user_type = models.CharField(choices=ROLE,max_length=15)
    Image = models.ImageField(upload_to='images/',validators=[validate_file_extension,validate_image])
   

class Assignment_Request(models.Model):
    teacher = models.ForeignKey( User,on_delete=models.CASCADE,null=True,related_name='teacherr')
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name='studentt')
    request = models.BooleanField(default=True)



def get_deadline():
    return datetime.today()+timedelta(days=10)


class Assignment(models.Model):
   
    teacher = models.ForeignKey( User,on_delete=models.CASCADE,null=True,related_name='teacher')
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name='student')
    description = models.CharField(max_length=255, blank=True)
    as_file = models.FileField(upload_to='documents/', validators=[validate_file1_extension])
    Submit_date = models.DateTimeField(default=get_deadline,blank=True)
    uploaded = models.DateTimeField(default=datetime.now,blank=True)







class Submission(models.Model):
   
    teacher = models.ForeignKey( User,on_delete=models.CASCADE,null=True,related_name='teachers')
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name='students')
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE, null=True,related_name='assignment')
    submitted_file = models.FileField(upload_to='documents/', validators=[validate_file1_extension])
    description = models.CharField(max_length=255, blank=True)
    Submitted_date = models.DateTimeField(default=datetime.now,blank=True)



STAR = (
      ('1star','1star'),
      ('2star','2star'),
      ('3star','3star'),
      ('4star','4star'),
      ('5star','5star'),
      
  )







class Remark(models.Model):
    teacher = models.ForeignKey( User,on_delete=models.CASCADE,null=True,related_name='teacherss')
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name='studentss') 
    assignment = models.ForeignKey(Submission, on_delete=models.CASCADE, null=True,related_name='assignments')
    rating = models.CharField(choices=STAR,max_length=25, null=True, blank=True)
    

   

class Messages(models.Model):

    sender = models.ForeignKey(User, related_name="sender", on_delete=models.CASCADE, null=True)
    receiver = models.ForeignKey(User, related_name="receiver", on_delete=models.CASCADE, null=True)
    msg = models.TextField(max_length=1000)
    timestamp = models.DateTimeField(default=datetime.now,blank=True)
    
    class Meta:
        verbose_name_plural = "Messages"
    
    def __str__(self):
        return str(self.id) + ": from " + str(self.sender) + " to " + str(self.receiver)

  

    

core/views.py
from django.shortcuts import render,redirect,reverse, get_object_or_404
from django.contrib.auth import authenticate,login as dj_login
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from django.template import RequestContext
# from django.contrib.auth.forms import CustomUserLoginForm
from .forms import SignUpForm,PasswordForm, LoginForm,UpdateProfile,AddStudentForm,AssignmentForm,AssignmenttForm,AssignmentForm1,ReviewForm,MessageForm
from django.contrib.auth.forms import PasswordChangeForm
# from .templates import  ValidCaptcha
import json
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from core.tokens import account_activation_token
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from friendship.models import Friend, Follow, FriendshipRequest, Block
from django.views.generic import View
from django import template
from django.db.models import Count
register = template.Library()
# from rest_framework.views import APIView
# from rest_framework.response import Response
# from rest_framework import status
# # from .serializers import  MessagesSerializer,UserProfileSerializer
from django.db.models import Q



from friendship.exceptions import AlreadyExistsError,AlreadyFriendsError
User = get_user_model()

get_friendship_context_object_name = lambda: getattr(
    settings, "FRIENDSHIP_CONTEXT_OBJECT_NAME", "user"
)
get_friendship_context_object_list_name = lambda: getattr(
    settings, "FRIENDSHIP_CONTEXT_OBJECT_LIST_NAME", "users"
)









def indexx(request):
     return render(request, 'layout.html')     




def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            # if Captcha.is_valid():
                user= form.save(commit=False)
                user.user_type = form.cleaned_data.get('user_type')
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Activate your blog account.'
                message = render_to_string('acc_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid':urlsafe_base64_encode(force_bytes(user.pk)) ,
                    'token':account_activation_token.make_token(user),
                })
                to_email = form.cleaned_data.get('email')
            
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()
                return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignUpForm()
        
    return render(request, 'registration/signup.html', {'form': form})



def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        dj_login(request, user)
        return HttpResponseRedirect(reverse('pass', args=(uid,)))
        # return redirect('pass')
    else:
        return HttpResponse('Activation link is invalid!')


# ---------set password after activation of link----------

def password(request,uid):
    if request.method == 'POST':
        form = PasswordForm(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=uid)
            password= request.POST.get('password')
            password= form.cleaned_data['password']
            user.set_password(password)
            user.save()
            dj_login(request,user)
            return redirect('login1')
    else:
         form = PasswordForm()    
    return render(request, "gen_pas.html", {'form': form})



# ----------same login for both teacher and student----------- 

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        user = authenticate(username=request.POST['username'] ,password=request.POST['password'])

        if user is not None:
            if user.is_active:
             dj_login(request, user)
            
            if user.user_type =='student':  
                return redirect('profile') 
            elif user.user_type =='teacher':
                return redirect('profile') 
    else:
        form = PasswordForm()    
        
    return render(request, "registration/login.html", {'form': form})        




# ---------different dashboard after login---------

@login_required
def profile(request):   
        user=request.user
        users = User.objects.all()
        if user.user_type =='teacher':
            return render(request, 'teacher_profile.html', {"users":users})
        elif user.user_type =='student':  
            return render(request, 'student_profile.html', {"users":users})
        else: 
            return redirect('layout.html')


# updation of profile--------------------

@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = UpdateProfile(request.POST, request.FILES , instance=request.user)
        
        if (user_form.is_valid()):
           
            user_form.save()            
            return HttpResponseRedirect(reverse('profile'))
        
    else:
        user_form = UpdateProfile(instance=request.user)
    if request.user.user_type =='student':    
        return render(request, 'registration/update_profile_student.html', {'user_form': user_form })
    if request.user.user_type =='teacher':  
        return render(request, 'registration/update_profile_teacher.html', {'user_form': user_form})      
    



#--------change password-----------

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            # messages.success(request, 'Your password was successfully updated!')
            return redirect('profile')
        else:
            pass
    else:
        form = PasswordChangeForm(request.user)
    if request.user.user_type =='teacher':      
        return render(request, 'change_password.html', {'form': form})
    if request.user.user_type =='student':
        return render(request, 'studentchange_password.html', {'form': form})    


# Teacher can add student----------------------- 

def addstudent(request):
    if request.user.user_type =='teacher':  
        if request.method == 'POST':
            form = AddStudentForm(request.POST)
            if form.is_valid():
                    user= form.save(commit=False)
                    user.user_type = form.cleaned_data.get('user_type')
                    user.is_active = False
                    user.save()
                    current_site = get_current_site(request)
                    mail_subject = 'Activate your blog account.'
                    message = render_to_string('acc_active_email.html', {
                        'user': user,
                        'domain': current_site.domain,
                        'uid':urlsafe_base64_encode(force_bytes(user.pk)) ,
                        'token':account_activation_token.make_token(user),
                    })
                    to_email = form.cleaned_data.get('email')
                
                    email = EmailMessage(mail_subject, message, to=[to_email])
                    email.send()
                    return HttpResponse('Please confirm your email address to complete the registration')
        else:
            form = AddStudentForm()
            
        return render(request, 'registration/add_student.html', {'form': form})   
    else:
        return render(request,'error.html')


 #   list of student in teacher dashboard---------------
def student_list(request): 
    if request.user.user_type =='teacher':    
        dataa=User.objects.filter(user_type = 'student')
        
        context = {
                'dataa':dataa 
        }
        return render(request,'student_list.html',context=context)    
    else:
        return render(request,'error.html')



#-----------list of teacher in student dashboard-----------

def teacher_list(request):   
    if request.user.user_type =='student':  
        dataa=User.objects.filter(user_type = 'teacher')
        
        context = {
                'dataa':dataa 
        }
        return render(request,'teacher_list.html',context=context)    
    else:
        return render(request,'error2.html')



# ---------------student dashboard for making request---------

def friendship_add_friend(request,teacher_id):
    if request.user.user_type =='student':  
        ctx = {"teacher_id": teacher_id}
        if request.method == "POST":
            print("dsad")
            to_user = User.objects.get(pk=teacher_id)
            from_user = request.user
            print(to_user)
            try:
                Friend.objects.add_friend(from_user,to_user)
                print("hghjgj")
            except AlreadyFriendsError as e:
                ctx["errors"] = ["%s" % e]
            else:
                return redirect("student_profile")

        return render(request,"friendship/friend/add.html",ctx)

core/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon"> 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <!-- Icon -->
    <link rel="stylesheet" href="{% static 'fonts/line-icons.css' %}">
    
    <!-- Owl carousel -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
    
    <!-- Animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- Main Style -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Responsive Style -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    
<body>
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}
#id_msg {
border-radius: 14px;}


.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: darkcyan;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}

.topnav-right {
  float: right;
}
.w3-container{
 
 text-align: center;

}
form{
                margin-left: 10px;
                text-align: center;
                float: left;
        }
.button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 10px 20px;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  margin-left: 5%;
}

.button:hover {
  background-color: green;
}
label{
        margin-top: 20px;
        width: 100px;
        height: 30px;
        
        background-color: #EAEAEA;
}
input[type=text],input[type=email]{
        margin-top: 20px;
        width: 200px;
        height: 25px;
}
h2{
  margin-top: 40px;
  text-align: center;
}
.edit{
        margin-top: 40px;
        margin-left: 30%;
        max-width: 400px;
        height: 550px;
        border: 1px solid lightgrey;
        background-color: #EAEAEA;
        margin-bottom: 20px;
      }


input#id_email {
    width: 50%;
    padding: 12px;
}

</style>
</head>
<body>

<div class="topnav">
    <a class="navbar-brand" href="{% url 'profile' %}">
    <I>Teacher</I>
  </a>


  <div class="topnav-right">
    <a href="{% url 'profile' %}">{{ user.username }}</a>
    <a href="{% url 'logout' %}">Logout</a>
  </div>
</div>
<div class="w3-sidebar w3-light-grey w3-bar-block" style="background-color: darkcyan;height:100%">
    <a href="{% url 'profile' %}" class="w3-bar-item w3-button">Profile</a>
    <a href="{% url 'change_password' %}" class="w3-bar-item w3-button">Change Password</a>
    <a href="{% url 'addstudent' %}" class="w3-bar-item w3-button">Add Student</a>
    <a href="{% url 'studentlist' %}" class="w3-bar-item w3-button">Students List</a>
    <a href="{% url 'request_list' %}" class="w3-bar-item w3-button">Accept the request</a>
    <a href="{% url 'accepted_trequest' user.id %}" class="w3-bar-item w3-button">Student joined you</a>
    <a href="{% url 'studentass_list' %}" class="w3-bar-item w3-button">Send Assignment</a>
    <a href="{% url 'check_ass' %}" class="w3-bar-item w3-button">Check Assignment</a>
    <a href="{% url 'check_messages' %}" class="w3-bar-item w3-button">Check messages</a>
    <a href="{% url 'logout' %}" class="w3-bar-item w3-button">Logout</a>
  </div>
    
            
              
  <div style="margin-left:20%">

       
      {% block content %}


      {% endblock %}
</div>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/wow.js' %}"></script>
    <script src="{% static 'js/jquery.nav.js' %}"></script>
    <script src="{% static 'js/scrolling-nav.js' %}"></script>
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>  
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/form-validator.min.js' %}"></script>
   
    <!-- <script src="{% static 'js/contact-form-script.min.js' %}"></script> -->
  </body>
</html> 

core/templates/base2.html
{% load static %}
<!DOCTYPE html>

<!------ Include the above in your HEAD tag ---------->

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="img/ico" href='images/favicon.png'>
    <title>hitgoalz</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/font-awesome.css">

    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/responsive.css">

    <script src="js/jquery-3.1.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base2.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="js/hitgoalz.js"></script>
    <script src="{% static 'js/base2.js' %}"></script>

    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon"> 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <!-- Icon -->
    <link rel="stylesheet" href="{% static 'fonts/line-icons.css' %}">
    
    <!-- Owl carousel -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
    
    <!-- Animate -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- Main Style -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <!-- Responsive Style -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">

<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}
#id_msg {
border-radius: 14px;}

.nav-item a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.nav-item a:hover {
  background-color: darkcyan;
  color: black;
}

.nav-item a.active {
  background-color: #4CAF50;
  color: white;
}

.topnav-right {
  float: left;
}



form{
                margin-left: 10px;
                text-align: center;
                float: left;
        }
.button {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 10px 20px;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
  margin-left: 5%;
}

.button:hover {
  background-color: green;
}
label{
        margin-top: 20px;
        width: 100px;
        height: 30px;
        
        background-color: #EAEAEA;
}
input[type=text],input[type=email]{
        margin-top: 20px;
        width: 200px;
        height: 25px;
}
h2{
  margin-top: 40px;
  text-align: center;
}
.edit{
        margin-top: 40px;
        margin-left: 30%;
        max-width: 400px;
        height: 550px;
        border: 1px solid lightgrey;
        background-color: #EAEAEA;
        margin-bottom: 20px;
      }


input#id_email {
    width: 50%;
    padding: 12px;
}
</style>








</head>

<body>
    <!--===============================================
                      NAVBAR
===============================================-->


    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="hamburger">
            <div class="cta">
                <div class="toggle-btn type14"></div>
            </div>
        </div>

        <!-- Brand/logo -->
        <a class="navbar-brand" href="{% url 'profile' %}">
    <I>STUDENTS</I>
  </a>

        <!-- Links -->

 <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile' %}">{{ user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            
        </ul>


    </nav>


    <section class="side-bar-warp">
        <div class="sidebar-menu small-side-bar flowHide">
            <nav class="">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">
                        <span class="sidebar-icon"><img src="images/dashboard.png" alt=""></span>
                        <span class="fadeInRight animated nav-link-name name-hide tax-show">Profile</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'change_password' %}">
                        <span class="sidebar-icon"><img src="images/create-quest.png" alt=""></span>
                        <span class="fadeInRight animated nav-link-name name-hide tax-show">Change Password</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'teacherlist' %}">
                        <span class="sidebar-icon"><img src="images/manage-quests.png" alt=""></span>
                        <span class="fadeInRight animated nav-link-name name-hide tax-show">Make Request to teachers</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accepted_request' user.id %}">
                        <span class="sidebar-icon"><img src="images/leaderboards.png" alt=""></span>
                        <span class="fadeInRight animated nav-link-name name-hide tax-show">Request assignment/Chat</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'submit_ass' %}">
                        <span class="sidebar-icon"><img src="images/one-on-one.png" alt=""></span>
                        <span class="fadeInRight animated nav-link-name name-hide tax-show">Submit Assignment</span>
                        </a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'check_remarks' %}">
                        <span class="sidebar-icon"><img src="images/give-kudos.png" alt=""></span>
                        <span class="fadeInRight animated nav-link-name name-hide tax-show">Review Remarks</span>
                       </a>
                    </li>

                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'check_tmessages' %}">
                        <span class="sidebar-icon"><img src="images/settings.png" alt=""></span>
                        <span class="fadeInRight animated nav-link-name name-hide tax-show">Check messages</span>
                        </a>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">
                        <span class="sidebar-icon"><img src="images/settings.png" alt=""></span>
                        <span class="fadeInRight animated nav-link-name name-hide tax-show">Logout</span>
                        </a>
                    </li>
            </nav>
        </div>
        
        
    </section>
<div style="margin-left:20%">

       
      {% block content %}


      {% endblock %}
</div>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/wow.js' %}"></script>
    <script src="{% static 'js/jquery.nav.js' %}"></script>
    <script src="{% static 'js/scrolling-nav.js' %}"></script>
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>  
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/form-validator.min.js' %}"></script>
   
    <!-- <script src="{% static 'js/contact-form-script.min.js' %}"></script> -->




</body>

</html>

core/templates/change_password.html
{% extends 'base1.html' %}
{% block content %}
<div class="section-header text-center" style="margin-top:5px; ">
    <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Here is your profile</h2>
    <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
  </div>
  <div class="container1" style="height: 500px;width:500px;">       
<h5 style="color: black">Welcome {{ user.username }}</h5>
<!-- <div class="w3-container" style="color:black"></div> -->
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"  style="margin-top: 10%;background-color: #4CAF50;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;">Save changes</button>
      </form>
</div>
    </div>
    {% endblock %}  
       